### PR TITLE
Various improvements in UX and robustness

### PR DESCRIPTION
**Pull request by Etenil**
Sorry I changed a lot of stuff, just though you might want to get some of the fixes.

- Fixed a number of bugs related to asynchronousness, variables
  being undefined when they should be defined etc.
- Added desktop notifications
- Automatically focus the text box when selecting a chat
- Reordered chats alphabetically
- List the same channels and IMs as the slack app
- Removed dependency on babel as es6 does all the original code
  needs

### CODE REVIEW

**Comment by bkanber** [comment]
Thanks for your contributions -- I hope to review within the next week!

**Comment by j6k4m8** [comment]
Love the refactor into a `ui` module!

**Comment by Etenil** [comment]
@j6k4m8 Thanks. I thought I could try to decouple some of the logic from the UI, but I'm not there yet.

There are still some problems I'm currently working on, namely:

- handle emojis, i.e. convert things like `:slightly_smiling_face:` to `:-)` back-and-forth
- marking messages read upon reception on the open channel doesn't quite work, I still receive email notifications :(
- Slackbot's previews for links don't always work, something it displays `undefined`
- long URLs get wrapped and can't be opened by the terminal. I'm trying to minify them automatically to mitigate the issue
- I started implementing slack's ctrl-t quick switcher but I need to get better with blessed
- threads don't seem to be working

**Comment by j6k4m8** [comment]
re: <kbd>ctrl</kbd><kbd>t</kbd> — don't forget that they've aliased <kbd>ctrl</kbd><kbd>k</kbd> as well :) I'd contribute to a custom keybindings PR if you push what you've got on that front.

When I played with the slack API previously, I found that certain "unfurled" links would come across as different JSON than others, depending on if Slack was able to access the endpoint or not. So it's possible that's why you're getting sporadic `undefined`s?

**Comment by bkanber** [comment]
Thanks for this. Merging this to a v0.2.0 branch and play with it for a bit before mainlining. I do want to keep babel as a dev dependency because not everyone is using latest node. And I think we need to play with channel sorting more but let's see how it plays during a real workweek. All in all great effort and I appreciate the contribution!

**Pull request merged**
